name: Backend Test

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  
defaults:
  run:
    working-directory: backend
  
jobs:
  test:
    name: Run golang test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Display Golang version
        run: go version
      - name: Install dependencies
        run: go mod download
      - name: Run test
        run: go test ./...